-- MySQL Script generated by MySQL Workbench
-- Fri Jan  6 06:00:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema urlshortener
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema urlshortener
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `urlshortener` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `urlshortener` ;

-- -----------------------------------------------------
-- Table `urlshortener`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urlshortener`.`admin` (
  `admin_id`  NOT NULL,
  `admin_mail` VARCHAR(150) NOT NULL,
  `admin_pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admin_mail`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `urlshortener`.`url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urlshortener`.`url` (
  `url_id`  NOT NULL,
  `main_url` VARCHAR(120) NULL DEFAULT NULL,
  `short_url` VARCHAR(45) NULL DEFAULT NULL,
  `expire_date` DATE NULL DEFAULT NULL,
  `create_date` DATE NULL DEFAULT NULL,
  `auth_mail` VARCHAR(120) NULL DEFAULT NULL,
  `counter_url`  NULL DEFAULT '1',
  PRIMARY KEY (`url_id`),
  UNIQUE INDEX `main_url_UNIQUE` (`main_url` ASC) VISIBLE,
  UNIQUE INDEX `short_url_UNIQUE` (`short_url` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 110
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `urlshortener`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urlshortener`.`user` (
  `user_id`  NOT NULL,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `user_s_name` VARCHAR(45) NULL DEFAULT NULL,
  `user_mail` VARCHAR(120) NULL DEFAULT NULL,
  `user_pass` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
